---
name: build-ui-bundle

on:
  push:
    branches: ["main", "devops-stack"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 12

    - name: Install Node.js dependencies
      run: npm ci

    - name: Run Gulp to create the ui-bundle.zip
      run: gulp bundle


    - name: Delete last release
      uses: dev-drprasad/delete-older-releases@v0.2.0
      with:
        keep_latest: 0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create new release with new ui-bundle.zip
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: "${{ github.ref_name }}-LATEST"
        name: "Release ${{ github.ref_name }}-LATEST"
        body: |
          Release of the DevOps Stack's Antora UI `ui-bundle.zip` for ${{ github.ref_name }}
        draft: false
        prerelease: false
        files: build/ui-bundle.zip
